print("Welcome to the tip calculator.")
total_bill = float(input("What was the totla bill? $"))
tip = int(input("What percentage tip would you like to give? 10, 12 or 15? "))
people = int(input("How many people to split the bill? "))
pay_per_person = round((((tip * total_bill) / 100) + total_bill) / people, 2)
print(f"Each person should pay : ${pay_per_person}")
